### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by arhen** [Naotonosato/Blawn#1]
I've read about your blawn programming language from [here ](https://github.com/Naotonosato/Blawn).

Is there any documentation about how to use this on my local machine? Like how to build or something similar.
thanks anyway for your contribution to open source.

**Comment by Naotonosato** [comment]
sorry but i'm not good at English, so please use google transition...

日本語で書きます。
基本的には"/Blawn "をダウンロードして頂ければ使えます。Blawnディレクトリの下のblawnというファイルが本体で、Blawn/tools/cridge.pyがcridgeの本体なので適時パスを通して頂ければ使用できます。
ただ、blawnはまだ安定版ではないのでBlawnの使用によっていかなる損害が出た場合でもこちらでは責任を負いかねます。

**Comment by Naotonosato** [comment]
それかもしソースからコンパイルしたい場合は、llvm6.0,bison,flex,clang をインストールしてからbuildディレクトリにて"make -j8"と入力すればコンパイルできます

**Comment by Naotonosato** [comment]
i'll write doc about installing and introduction. sorry but please wait.

**Comment by arhen** [comment]
Ok. Thanks For your comment. I'll try and wait for official documentation!
